Add untested uppercasing to `hello-roc`
`roc` compiler is panicking :( I'm too lazy to roll back the update
right now.

```
$ roc run src/roc/hello/main.roc
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at crates/compiler/can/src/expr.rs:1130:41:
a Expr::TaskAwaitBang expression was not completed removed in desugar_value_def_suffixed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


There was an unrecoverable error in the Roc compiler. The `roc check` command can sometimes give a more helpful error report than other commands.
```